"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ArrowPathIcon, CheckCircleIcon, ChevronDownIcon, ExclamationTriangleIcon } from "@heroicons/react/24/outline";

export const dynamic = "force-dynamic";
const PAGE_SIZES = [25, 50, 100];
const TYPES = ["all", "sparkling", "white", "rosé", "red", "orange", "dessert", "fortified", "sake"];
const number = (value) => Number(value || 0);
const quantity = (value) => new Intl.NumberFormat("en-GB", { maximumFractionDigits: 2 }).format(Math.abs(number(value)) < 0.001 ? 0 : number(value));
const money = (value) => new Intl.NumberFormat("en-EE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(number(value));
const syncDate = (value) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "Not yet completed";

function Kpi({ label, value, detail, active, onClick, tone = "default" }) {
  const colour = tone === "warning" ? "text-[#a95836]" : tone === "good" ? "text-[#607758]" : "text-[#30241f]";
  const content = <><div className="text-[8px] uppercase tracking-[0.22em] text-[#a29184]">{label}</div><div className={`mt-2 text-[22px] tracking-[-0.035em] ${colour}`}>{value}</div><div className="mt-1 text-[8px] leading-4 text-[#9a8a7f]">{detail}</div></>;
  return onClick ? <button type="button" onClick={onClick} className={`bg-[#fbf8f3] px-5 py-4 text-left transition hover:bg-[#f5eee7] ${active ? "shadow-[inset_0_-2px_0_#963d2d]" : ""}`}>{content}</button> : <div className="bg-[#fbf8f3] px-5 py-4">{content}</div>;
}

export default function WineInventoryPage() {
  const supabase = useMemo(() => createClient(), []);
  const [inventory, setInventory] = useState([]); const [locations, setLocations] = useState([]); const [latestSync, setLatestSync] = useState(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [search, setSearch] = useState(""); const [selectedLocation, setSelectedLocation] = useState("all"); const [selectedType, setSelectedType] = useState("all"); const [stockFilter, setStockFilter] = useState("available"); const [sortBy, setSortBy] = useState("name"); const [sortDirection, setSortDirection] = useState("asc"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25); const [expandedWineId, setExpandedWineId] = useState(null);

  async function loadData() {
    setLoading(true); setLoadError("");
    const [inventoryResult, locationsResult, syncResult] = await Promise.all([
      supabase.from("wine_inventory").select("id,wine_id,location_id,quantity,wines(id,name,producer,vintage,price,wine_type,country,region,subregion,grapes,size,sku),wine_locations(id,name)"),
      supabase.from("wine_locations").select("id,name,location_type").order("name"),
      supabase.from("compucash_sync_runs").select("status,completed_at,products_matched,unmatched_products,error_message").order("created_at", { ascending: false }).limit(1).maybeSingle(),
    ]);
    if (inventoryResult.error || locationsResult.error) setLoadError(inventoryResult.error?.message || locationsResult.error?.message || "Inventory could not be loaded.");
    setInventory(inventoryResult.data || []); setLocations(locationsResult.data || []); setLatestSync(syncResult.data || null); setLoading(false);
  }

  useEffect(() => { loadData(); }, []);
  useEffect(() => { setPage(1); }, [search, selectedLocation, selectedType, stockFilter, pageSize]);

  const wines = useMemo(() => {
    const map = new Map();
    inventory.forEach((row) => { const wine = row.wines; if (!wine?.id) return; if (!map.has(wine.id)) map.set(wine.id, { ...wine, stock: 0, inventoryRows: [] }); const entry = map.get(wine.id); entry.stock += number(row.quantity); entry.inventoryRows.push(row); });
    return Array.from(map.values());
  }, [inventory]);
  const metrics = useMemo(() => ({ positiveUnits: wines.reduce((sum, wine) => sum + Math.max(0, wine.stock), 0), available: wines.filter((wine) => wine.stock > 0).length, low: wines.filter((wine) => wine.stock > 0 && wine.stock <= 2).length, out: wines.filter((wine) => wine.stock <= 0).length, negative: wines.filter((wine) => wine.stock < -0.001).length, value: wines.reduce((sum, wine) => sum + Math.max(0, wine.stock) * number(wine.price), 0) }), [wines]);
  const filteredWines = useMemo(() => {
    const q = search.trim().toLowerCase();
    return wines.filter((wine) => { const haystack = [wine.name, wine.producer, wine.country, wine.region, wine.subregion, wine.grapes, wine.vintage, wine.sku].join(" ").toLowerCase(); const locationMatch = selectedLocation === "all" || wine.inventoryRows.some((row) => row.location_id === selectedLocation && number(row.quantity) > 0); const typeMatch = selectedType === "all" || String(wine.wine_type || "").toLowerCase() === selectedType; const stockMatch = stockFilter === "all" || (stockFilter === "available" && wine.stock > 0) || (stockFilter === "low" && wine.stock > 0 && wine.stock <= 2) || (stockFilter === "out" && wine.stock <= 0); return (!q || haystack.includes(q)) && locationMatch && typeMatch && stockMatch; }).sort((a, b) => { let av = sortBy === "stock" ? a.stock : a[sortBy]; let bv = sortBy === "stock" ? b.stock : b[sortBy]; if (sortBy === "price") { av = number(av); bv = number(bv); } if (typeof av === "string") av = av.toLowerCase(); if (typeof bv === "string") bv = bv.toLowerCase(); return av < bv ? (sortDirection === "asc" ? -1 : 1) : av > bv ? (sortDirection === "asc" ? 1 : -1) : 0; });
  }, [wines, search, selectedLocation, selectedType, stockFilter, sortBy, sortDirection]);
  const totalPages = Math.max(1, Math.ceil(filteredWines.length / pageSize)); const safePage = Math.min(page, totalPages); const start = (safePage - 1) * pageSize; const pageWines = filteredWines.slice(start, start + pageSize);
  const sort = (column) => { if (sortBy === column) setSortDirection((value) => value === "asc" ? "desc" : "asc"); else { setSortBy(column); setSortDirection("asc"); } };
  const sortLabel = (label, column) => <button type="button" onClick={() => sort(column)} className="inline-flex items-center gap-2">{label}<span className={sortBy === column ? "text-[#963d2d]" : "text-[#c5b6aa]"}>{sortBy === column ? (sortDirection === "asc" ? "↑" : "↓") : "↕"}</span></button>;
  const syncHealthy = latestSync?.status === "succeeded";

  return <div className="min-h-screen bg-[#f7f3ed] text-[#30241f]"><div className="mx-auto max-w-[1700px] px-5 py-7 md:px-8 lg:px-10">
    <header className="flex flex-col gap-5 border-b border-[#ded3c8] pb-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[9px] uppercase tracking-[0.34em] text-[#a17865]">Wine Operations</div><h1 className="mt-3 text-[34px] font-medium tracking-[-0.04em] md:text-[44px]">Stock Control</h1><p className="mt-2 max-w-[680px] text-[11px] leading-5 text-[#8a7b70]">See what is available and where it is stored. Quantities are read-only because Compucash is the source of truth.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={loadData} disabled={loading} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-[#d5c5b9] bg-[#fbf8f3] px-4 text-[9px] uppercase tracking-[0.14em]"><ArrowPathIcon className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />Refresh</button><Link href="/dashboard/wines" className="inline-flex min-h-10 items-center rounded-full bg-[#963d2d] px-5 text-[9px] uppercase tracking-[0.14em] text-white">Manage wine catalogue</Link></div></header>

    <section className={`mt-5 flex flex-col gap-3 rounded-[18px] border px-4 py-3 sm:flex-row sm:items-center sm:justify-between ${syncHealthy ? "border-[#d5dfcf] bg-[#eff4ec]" : "border-[#ead2c4] bg-[#f8ebe3]"}`}><div className="flex items-center gap-3">{syncHealthy ? <CheckCircleIcon className="h-5 w-5 text-[#647c5c]" /> : <ExclamationTriangleIcon className="h-5 w-5 text-[#a95836]" />}<div><div className="text-[10px] font-medium">{syncHealthy ? "Compucash inventory is connected" : "Compucash sync needs attention"}</div><div className="mt-0.5 text-[9px] text-[#7f7066]">Last completed {syncDate(latestSync?.completed_at)}</div></div></div><div className="text-[9px] text-[#7f7066]">{latestSync ? `${number(latestSync.products_matched).toLocaleString("en-GB")} matched · ${number(latestSync.unmatched_products).toLocaleString("en-GB")} unmatched` : "No synchronization history"}</div></section>

    <section className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-[20px] border border-[#ded3c8] bg-[#ded3c8] xl:grid-cols-5"><Kpi label="Tracked wines" value={wines.length.toLocaleString("en-GB")} detail="Products with inventory records" /><Kpi label="Positive units" value={quantity(metrics.positiveUnits)} detail={`Across ${locations.length} locations`} /><Kpi label="Available" value={metrics.available.toLocaleString("en-GB")} detail="Wines with positive stock" active={stockFilter === "available"} onClick={() => setStockFilter("available")} tone="good" /><Kpi label="Low stock" value={metrics.low.toLocaleString("en-GB")} detail="Positive balance of 2 or less" active={stockFilter === "low"} onClick={() => setStockFilter("low")} tone="warning" /><Kpi label="Out of stock" value={metrics.out.toLocaleString("en-GB")} detail={metrics.negative ? `${metrics.negative} negative balances need review` : "No positive balance"} active={stockFilter === "out"} onClick={() => setStockFilter("out")} tone="warning" /></section>

    <section className="mt-5 overflow-hidden rounded-[22px] border border-[#ded3c8] bg-[#fbf8f3]"><div className="border-b border-[#e4dad1] p-4"><div className="grid gap-3 xl:grid-cols-[1fr_180px_210px_180px_auto]"><label><span className="mb-1.5 block text-[8px] uppercase tracking-[0.16em] text-[#9b897e]">Search catalogue</span><input aria-label="Search catalogue" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Wine, producer, region, vintage or SKU…" className="min-h-11 w-full rounded-xl border border-[#ddd0c5] bg-white/70 px-4 text-[11px] outline-none" /></label><Filter label="Wine type" value={selectedType} onChange={setSelectedType}>{TYPES.map((type) => <option key={type} value={type}>{type === "all" ? "All types" : type}</option>)}</Filter><Filter label="Location" value={selectedLocation} onChange={setSelectedLocation}><option value="all">All locations</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</Filter><Filter label="Stock state" value={stockFilter} onChange={setStockFilter}><option value="all">All states</option><option value="available">Available</option><option value="low">Low stock ≤ 2</option><option value="out">Out of stock</option></Filter><button type="button" onClick={() => { setSearch(""); setSelectedType("all"); setSelectedLocation("all"); setStockFilter("available"); }} className="self-end px-4 pb-3 text-[8px] uppercase tracking-[0.18em] text-[#8d7567]">Reset filters</button></div></div>
      <div className="flex flex-col gap-2 border-b border-[#e4dad1] px-5 py-3 text-[9px] text-[#95867b] sm:flex-row sm:items-center sm:justify-between"><span>Showing {filteredWines.length ? start + 1 : 0}–{Math.min(start + pageSize, filteredWines.length)} of {filteredWines.length} wines</span><label className="flex items-center gap-2">Rows<select value={pageSize} onChange={(e) => setPageSize(number(e.target.value))} className="rounded-lg border border-[#ddd0c5] bg-white px-2 py-1">{PAGE_SIZES.map((size) => <option key={size}>{size}</option>)}</select></label></div>
      {loadError ? <div className="px-5 py-16 text-center text-[11px] text-red-600">{loadError}</div> : <div className="w-full overflow-x-auto"><table className="w-full min-w-[780px] table-fixed border-collapse"><thead><tr className="border-b border-[#ded3c8] text-[8px] uppercase tracking-[0.18em] text-[#a18f82]"><th className="w-[31%] px-5 py-4 text-left font-normal">{sortLabel("Wine", "name")}</th><th className="w-[12%] px-4 py-4 text-left font-normal">{sortLabel("Type", "wine_type")}</th><th className="w-[27%] px-4 py-4 text-left font-normal">Locations</th><th className="w-[12%] px-4 py-4 text-right font-normal">{sortLabel("Quantity", "stock")}</th><th className="w-[10%] px-4 py-4 text-right font-normal">{sortLabel("Price", "price")}</th><th className="w-[8%] px-5 py-4 text-right font-normal">Details</th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="px-5 py-16 text-center text-[11px] text-[#95867b]">Loading Compucash inventory…</td></tr> : pageWines.length ? pageWines.map((wine) => <WineRow key={wine.id} wine={wine} expanded={expandedWineId === wine.id} onToggle={() => setExpandedWineId((current) => current === wine.id ? null : wine.id)} />) : <tr><td colSpan="6" className="px-5 py-16 text-center"><div className="text-[12px] font-medium">No wines match these filters</div><div className="mt-2 text-[9px] text-[#95867b]">Reset the filters or choose another location.</div></td></tr>}</tbody></table></div>}
      <div className="flex flex-col gap-3 border-t border-[#e4dad1] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="text-[9px] text-[#95867b]">Page {safePage} of {totalPages}</div><div className="flex items-center gap-2"><PageButton disabled={safePage === 1} onClick={() => setPage(1)}>First</PageButton><PageButton disabled={safePage === 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</PageButton><span className="min-w-16 text-center text-[9px] text-[#806d60]">{safePage} / {totalPages}</span><PageButton disabled={safePage === totalPages} onClick={() => setPage((value) => Math.min(totalPages, value + 1))}>Next</PageButton><PageButton disabled={safePage === totalPages} onClick={() => setPage(totalPages)}>Last</PageButton></div></div>
    </section>
  </div></div>;
}

function Filter({ label, value, onChange, children }) { return <label><span className="mb-1.5 block text-[8px] uppercase tracking-[0.16em] text-[#9b897e]">{label}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 w-full rounded-xl border border-[#ddd0c5] bg-white/70 px-3 text-[10px] capitalize outline-none">{children}</select></label>; }
function PageButton({ children, ...props }) { return <button type="button" {...props} className="h-9 rounded-full border border-[#d9cbc0] px-3 text-[9px] disabled:opacity-30">{children}</button>; }
function WineRow({ wine, expanded, onToggle }) {
  const positiveLocations = wine.inventoryRows.filter((row) => number(row.quantity) > 0).sort((a, b) => number(b.quantity) - number(a.quantity));
  const visible = positiveLocations.slice(0, 2);
  const state = wine.stock <= 0 ? "Out" : wine.stock <= 2 ? "Low" : "Available";
  const stateClass = state === "Available" ? "bg-[#e6eee2] text-[#607758]" : state === "Low" ? "bg-[#f3e6da] text-[#9b603d]" : "bg-[#f1ddda] text-[#a34f42]";
  return <><tr className="border-b border-[#ebe3dc] transition hover:bg-[#f7f1eb]"><td className="px-5 py-3"><div className="truncate text-[11px] font-medium md:text-[12px]">{wine.name || "Unnamed wine"}</div><div className="mt-1 text-[9px] text-[#94847a]">{[wine.producer, wine.vintage || "NV"].filter(Boolean).join(" · ")}</div></td><td className="px-4 py-3"><span className="rounded-full border border-[#dfd1c5] px-2.5 py-1 text-[8px] capitalize text-[#806d60]">{wine.wine_type || "—"}</span></td><td className="px-4 py-3"><div className="flex flex-wrap gap-1.5">{visible.length ? visible.map((row) => <span key={row.id} className="rounded-full bg-[#eee5dc] px-2.5 py-1 text-[8px] text-[#756357]">{row.wine_locations?.name || "Unknown"} · {quantity(row.quantity)}</span>) : <span className="text-[9px] text-[#b09f94]">No positive stock</span>}{positiveLocations.length > 2 && <span className="rounded-full bg-[#eee5dc] px-2.5 py-1 text-[8px]">+{positiveLocations.length - 2}</span>}</div></td><td className="px-4 py-3 text-right"><div className="text-[11px] font-medium">{quantity(Math.max(0, wine.stock))}</div><span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[7px] uppercase tracking-[0.12em] ${stateClass}`}>{state}</span></td><td className="px-4 py-3 text-right text-[10px]">{wine.price == null ? "—" : money(wine.price)}</td><td className="px-5 py-3 text-right"><button type="button" onClick={onToggle} aria-expanded={expanded} aria-label={`${expanded ? "Hide" : "Show"} details for ${wine.name}`} className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-[#d7c7bb]"><ChevronDownIcon className={`h-3.5 w-3.5 transition ${expanded ? "rotate-180" : ""}`} /></button></td></tr>{expanded && <tr className="border-b border-[#ded3c8] bg-[#f7f1eb]"><td colSpan="6" className="px-5 py-4"><div className="grid gap-4 md:grid-cols-[1fr_auto]"><div><div className="text-[8px] uppercase tracking-[0.18em] text-[#9a887c]">Stock by location</div><div className="mt-2 flex flex-wrap gap-2">{wine.inventoryRows.slice().sort((a, b) => number(b.quantity) - number(a.quantity)).map((row) => <div key={row.id} className="rounded-[12px] border border-[#ded3c8] bg-[#fbf8f3] px-3 py-2"><div className="text-[9px] font-medium">{row.wine_locations?.name || "Unknown location"}</div><div className="mt-1 text-[9px] text-[#89776c]">{quantity(row.quantity)} units</div></div>)}</div></div><div className="md:text-right"><div className="text-[8px] uppercase tracking-[0.18em] text-[#9a887c]">Inventory source</div><div className="mt-2 inline-flex rounded-full border border-[#d4dfcf] bg-[#edf3e9] px-3 py-1.5 text-[8px] uppercase tracking-[0.13em] text-[#5e7657]">Compucash · read only</div><div className="mt-2 text-[8px] leading-4 text-[#9a887c]">Correct quantities in Compucash.<br />Vaxeron updates automatically.</div></div></div></td></tr>}</>;
}
