import PublicInfoPage from "@/components/public/PublicInfoPage";
import { legalIdentity } from "@/lib/site/legal";

export const metadata = { title: "Pilot terms", description: "Terms governing access to the VAXERON private pilot." };

const sections = [
  { title: "Status of these terms", content: <><p>These provisional terms apply to the current invite-only VAXERON private pilot. They are not a substitute for the SaaS agreement, order form, service levels and Data Processing Agreement that will accompany commercial service. Registered operator details will be added when the legal entity is established.</p></> },
  { title: "Access and eligibility", content: <><p>Access is limited to invited hospitality organizations and their authorized team members. You must provide accurate information, keep credentials confidential and use only the workspace and permissions assigned to you. An organization administrator is responsible for authorized users within its workspace.</p></> },
  { title: "Acceptable use", content: <><p>You must not attempt to bypass access controls, enter another customer&apos;s workspace, probe or disrupt the service, upload unlawful or harmful material, misuse integrations, or use VAXERON in a way that infringes another person&apos;s rights. Suspected security issues should be reported to <a href={`mailto:${legalIdentity.emails.security}`}>{legalIdentity.emails.security}</a>.</p></> },
  { title: "Customer content and operational decisions", content: <><p>The customer remains responsible for the accuracy, legality and suitability of information it supplies or publishes. Inventory, pricing, allergens, guest information and generated descriptions should be reviewed by an authorized person before operational or guest-facing use. VAXERON does not replace professional, accounting, safety or legal judgement.</p></> },
  { title: "Integrations", content: <><p>Connected services are enabled at the customer&apos;s request and may be subject to their own terms, availability and data quality. Customers must have authority to connect each service. A source system may remain the operational source of truth where the relevant workflow says so.</p></> },
  { title: "Intellectual property", content: <><p>Customers retain rights in their content and grant the limited permission needed to host, process, display and support it. VAXERON and its software, design, documentation and branding remain protected by applicable intellectual-property law. Feedback may be used to improve the product without identifying the contributor.</p></> },
  { title: "Pilot availability and liability", content: <><p>The pilot may change, contain defects or be temporarily unavailable. No service level is promised unless separately agreed in writing. To the extent permitted by law, the pilot is provided without implied warranties and is not intended for safety-critical use. Nothing here excludes liability that cannot legally be excluded.</p></> },
  { title: "Suspension, exit and governing law", content: <><p>Access may be restricted where necessary to protect the service, comply with law or address misuse. Either party may end pilot participation by written notice, subject to an agreed data export or deletion process. These provisional terms are governed by Estonian law, without limiting mandatory rights that apply by law.</p><p>Questions may be sent to <a href={`mailto:${legalIdentity.emails.general}`}>{legalIdentity.emails.general}</a>.</p></> },
];

export default function TermsPage(){return <PublicInfoPage eyebrow="Legal · Private pilot" title="Pilot terms" intro="The practical rules for using VAXERON safely and responsibly while the commercial service and its operating company are being established." sections={sections}/>}
