"use client";

import { useMemo, useState } from "react";
const HEX_COLOR = /^#[0-9a-fA-F]{6}$/;

export default function AppearanceSettingsForm({ initialPrimaryColor, initialBackgroundStyle, initialCardStyle, initialDensity }) {
  const initial = useMemo(() => ({ primaryColor: HEX_COLOR.test(initialPrimaryColor || "") ? initialPrimaryColor : "#35594e", backgroundStyle: initialBackgroundStyle || "light", cardStyle: initialCardStyle || "solid", density: initialDensity || "cozy" }), [initialPrimaryColor, initialBackgroundStyle, initialCardStyle, initialDensity]);
  const [values, setValues] = useState(initial); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(null);
  const dirty = JSON.stringify(values) !== JSON.stringify(initial); const validColor = HEX_COLOR.test(values.primaryColor);
  const set = (key, value) => { setValues((current) => ({ ...current, [key]: value })); setMessage(null); };
  async function handleSave(event) { event.preventDefault(); if (!validColor) return setMessage({ type: "error", text: "Use a six-digit hex colour, for example #963d2d." }); setSaving(true); setMessage(null); try { const response = await fetch("/api/settings/appearance", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Unable to save appearance."); setMessage({ type: "success", text: "Guest appearance saved." }); } catch (error) { setMessage({ type: "error", text: error.message }); } finally { setSaving(false); } }
  return <form onSubmit={handleSave}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-[8px] uppercase tracking-[0.24em] text-[#758a83]">Presentation defaults</div><h3 className="mt-1 text-[16px] font-semibold tracking-[-0.03em]">Appearance</h3><p className="mt-1 text-[9px] leading-4 text-[#81908b]">Applies where a guest experience uses shared workspace styling.</p></div><div className="flex min-w-[150px] items-center gap-3 rounded-[13px] border border-[#20322e]/10 bg-[#f4f7f4] p-3"><div className="h-9 w-9 rounded-[10px] border border-black/10" style={{ backgroundColor: validColor ? values.primaryColor : "#ffffff" }} /><div><div className="text-[8px] uppercase tracking-[0.16em] text-[#82928c]">Preview</div><div className="mt-1 text-[10px] font-medium">Accent colour</div></div></div></div>
    <div className="mt-6 grid gap-5 md:grid-cols-2"><label className="block"><span className="text-[10px] font-medium">Primary colour</span><span className="mt-1 block text-[9px] leading-4 text-[#95857a]">Buttons, highlights and important guest actions.</span><div className="mt-2 flex gap-2"><input aria-label="Primary colour picker" type="color" value={validColor ? values.primaryColor : "#963d2d"} onChange={(e) => set("primaryColor", e.target.value)} className="h-10 w-12 cursor-pointer rounded-[10px] border border-[#d9ccc1] bg-white p-1" /><input aria-label="Primary colour hex value" value={values.primaryColor} onChange={(e) => set("primaryColor", e.target.value)} className={`h-10 flex-1 rounded-[10px] border bg-white px-3 text-[11px] outline-none ${validColor ? "border-[#d9ccc1] focus:border-[#a77561]" : "border-red-400"}`} /></div></label><Field label="Background" description="Overall guest-page atmosphere." value={values.backgroundStyle} onChange={(value) => set("backgroundStyle", value)} options={[["light","Light"],["dark","Dark"]]} /><Field label="Card style" description="Presentation and contrast of content cards." value={values.cardStyle} onChange={(value) => set("cardStyle", value)} options={[["solid","Solid"],["glass","Glass"]]} /><Field label="Layout density" description="Spacing used on supported guest interfaces." value={values.density} onChange={(value) => set("density", value)} options={[["cozy","Cozy"],["compact","Compact"]]} /></div>
    <div className="mt-6 flex flex-wrap items-center gap-3 border-t border-[#20322e]/9 pt-5"><button type="submit" disabled={saving || !dirty || !validColor} className="rounded-full bg-[#294039] px-5 py-2.5 text-[9px] uppercase tracking-[0.15em] text-white disabled:cursor-not-allowed disabled:opacity-40">{saving ? "Saving…" : dirty ? "Save changes" : "Up to date"}</button>{message && <span className={`text-[9px] ${message.type === "success" ? "text-[#5f7858]" : "text-red-600"}`}>{message.text}</span>}</div></form>;
}
function Field({ label, description, value, onChange, options }) { return <label className="block"><span className="text-[10px] font-medium">{label}</span><span className="mt-1 block text-[9px] leading-4 text-[#81908b]">{description}</span><select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 h-10 w-full rounded-[10px] border border-[#20322e]/12 bg-white px-3 text-[11px] outline-none focus:border-[#55766b]">{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>; }
