import PublicInfoPage from "@/components/public/PublicInfoPage";
import { legalIdentity } from "@/lib/site/legal";

export const metadata = { title: "Privacy notice", description: "How VAXERON handles personal data during its private pilot." };

const mail = <a href={`mailto:${legalIdentity.emails.privacy}`}>{legalIdentity.emails.privacy}</a>;
const sections = [
  { title: "Who is responsible", content: <><p>VAXERON is currently an invite-only private pilot based in Estonia. Its legal operating entity is being established. Until the registered entity details are published, privacy enquiries and requests can be sent to {mail}. The completed controller identity, registry code and registered address will be added before commercial launch.</p></> },
  { title: "Information we handle", content: <><p>Depending on how you use VAXERON, we may handle:</p><ul><li>name, business email address, role, organization and property information;</li><li>account invitations, authentication events and access permissions;</li><li>support messages and information you choose to provide;</li><li>technical records such as IP address, device, browser, timestamps and security logs;</li><li>operational hospitality data submitted by a customer or received from an enabled integration;</li><li>website preferences and analytics information, but only where the required consent has been obtained.</li></ul><p>VAXERON is designed for hospitality businesses and is not intended for children.</p></> },
  { title: "Why we use it", content: <><ul><li>To provide, secure and administer the requested workspace and guest experiences.</li><li>To authenticate users, apply roles and keep customer workspaces separated.</li><li>To support customers, investigate errors and improve reliability.</li><li>To operate integrations requested by the customer.</li><li>To comply with legal duties and protect VAXERON, its customers and users.</li></ul><p>The applicable legal basis may be performance of a contract or requested pre-contractual steps, legitimate interests in operating and securing the pilot, compliance with law, or consent where consent is required.</p></> },
  { title: "Customer data and roles", content: <><p>For workspace data, the hospitality customer generally determines why personal data is used and VAXERON processes it on that customer&apos;s instructions. For account administration, website operation, security and direct enquiries, VAXERON may act as controller. Commercial customers will receive a separate Data Processing Agreement before launch.</p></> },
  { title: "Service providers and transfers", content: <><p>VAXERON uses specialist infrastructure providers to deliver the service. The current categories and providers are documented on the <a href="/subprocessors">Subprocessors page</a>. Where data is transferred outside the European Economic Area, appropriate transfer safeguards supplied by the provider are used where required.</p><p>We do not sell personal data.</p></> },
  { title: "Retention", content: <><p>Information is retained only for as long as needed for the pilot, the customer relationship, security, dispute handling and applicable legal requirements. Account and workspace records are reviewed when access ends. Security logs and backups may remain for a limited period before scheduled deletion. Customer-specific retention and export terms will be defined in the commercial agreement.</p></> },
  { title: "Your rights", content: <><p>Subject to the GDPR and applicable limits, you may request access, correction, deletion, restriction, portability or objection, and may withdraw consent where processing relies on consent. Contact {mail}. We may need to verify your identity. You may also complain to the <a href="https://www.aki.ee/en" rel="noreferrer">Estonian Data Protection Inspectorate</a> or your local supervisory authority.</p></> },
  { title: "Security and changes", content: <><p>VAXERON uses access controls, authenticated sessions, tenant-scoped data access and infrastructure security measures appropriate to the pilot. No online service is risk-free. Material changes to this notice will be dated and published here.</p></> },
];

export default function PrivacyPage(){return <PublicInfoPage eyebrow="Legal · Data protection" title="Privacy notice" intro="A clear account of the personal data used to operate VAXERON, why it is needed and the choices available to you." sections={sections}/>}
